### ISSUE TITLE
Now that there is a x86 version of the PIXEL / Raspbian

### ISSUE THREAD

**Issue by ghost** [JuliaBerry/juliaberry.github.io#1]
now that there is a x86 version of the PIXEL Raspbian OS
it would be great to see an easy way to install Julia on that too

currently the 'apt-get install julia' method works 
but only gets Julia 0.3.2
and it errors on 'Pkg.update()'

sadly I'm just an old scriptkiddie and I wouldn't know much about how to fix that.

keep up the good work!
Julia has a great future in the Maker/Hacker &  6 - 12 EDU 

peace

**Comment by simonbyrne** [comment]
Good point, I've moved this to https://github.com/JuliaBerry/julia-raspbian/issues/3
