### ISSUE TITLE
Compile error raspberry pi CXX flag set wrong

### ISSUE THREAD

**Issue by jimcruse** [JuliaBerry/juliaberry.github.io#4]
Try compiling with raspberry pi 3b+
Get the following make error

fr /home/pi/git/julia/julia/usr/lib/julia
rm -fr /home/pi/git/julia/julia/usr/share/julia/extras
pi@raspberrypi:~/git/julia/julia $ make
/home/pi/git/julia/julia/deps/llvm.mk:571: *** Attempting to use gcc4 LLVM tarball, but compiling with cxx11 string ABI; set "CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0" to avoid linker errors.  Stop.
Makefile:60: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2
pi@raspberrypi:~/git/julia/julia $

**Comment by aviks** [comment]
It is not easy to compile on the pi itself, since it has very little memory. Use the precompiled binaries from https://julialang.org/downloads . If you absolutely want to compile from source, use the qemu/docker based setup here: https://github.com/Julia-Embedded/jlcross

**Comment by aviks** [comment]
To clarify, use the 32-bit arm files from the download location.
